### ISSUE TITLE
你好,快键键不生效

### ISSUE THREAD

**Issue by zzhi191** [xiebruce/PicUploader#29]
报错如下:

File "/Users/zhangzhi/code/PicUploader/accessorys/PicUploaderHelper/PicUploaderHelper.py", line 47, in <module>
    config = read_config()
  File "/Users/zhangzhi/code/PicUploader/accessorys/PicUploaderHelper/PicUploaderHelper.py", line 34, in read_config
    val = params[1]
IndexError: list index out of range

**Comment by xiebruce** [comment]
是有这个问题，因为之前打算转向用Alfred来使用，所以把单独使用的情况给忽略了，现在已经修复了，我测试了没问题了，你更新一下就可以。

不过如果你能用Alfred，我建议还是用Alfred，单独使用有时候快捷键设置不方便(由于使用的监听快捷键的python库本身bug，有些快捷键无法设置，一设置就报错)，开机自启动也不方便。

**Comment by zzhi191** [comment]
非常感谢你的付出,
我更新了最新代码,还是之前的错误,
我的一台mac 10.14 系统,完全没有问题.

这台电脑系统 10.15.1, 

用了Alfred,但是按下快捷键后,剪切板上图像并不能上传到图床,错误日志显示:
[19:20:49.218] Logging Started...
[19:20:58.085] PicUploaderHelper[Hotkey] Processing complete
[19:20:58.089] PicUploaderHelper[Hotkey] Passing output '' to Run Script
[19:20:58.549] STDERR: PicUploaderHelper[Run Script] pngpaste: Could not write to file!
[19:20:58.553] PicUploaderHelper[Run Script] Processing complete
[19:20:58.554] PicUploaderHelper[Run Script] Passing output '' to Copy to Clipboard

------
然后直接用python 设置快捷键的方法,拉取最新代码后,重新运行 generatesh.sh 文件,然后 sudo ./PicUploaderHelper-start.sh 生成log提示如下:

Traceback (most recent call last):
  File "/Users/zhangzhi/code/PicUploader/accessorys/PicUploaderHelper/PicUploaderHelper.py", line 47, in <module>
    config = read_config()
  File "/Users/zhangzhi/code/PicUploader/accessorys/PicUploaderHelper/PicUploaderHelper.py", line 34, in read_config
    val = params[1]
IndexError: list index out of range

**Comment by xiebruce** [comment]
1、mac 10.14完全没问题，是用Alfred没问题还是用python快捷键的方式没问题？
2、10.15.1系统我没有更新，所以我没遇到你说的问题，目测是由于所使用的`pngpaste`的更新没有跟上mac的最新系统，这个暂时无解；
3、用python设置快捷键的方式还是不行，应该是你没更新到，你把`PicUploaderHelper.py`的第32-44行截图上来我看看，或者你自己对比一下跟我这里是不是一样？
![image](https://user-images.githubusercontent.com/13575500/69721002-d9f42980-114e-11ea-8298-742abfd634b4.png)

**Comment by zzhi191** [comment]
太棒了,确实代码没有拿到最新,python 快键键的方式的问题已经解决,谢谢你.

Alfred 暂时不行,
不过我用 python的快捷键就OK,
工具很方便,大赞 😁

**Comment by xiebruce** [comment]
@zzhi191 好的，Alfred的不行是因为要借助pngpaste，但是pngpaste的更新没跟上mac的最新系统，所以有问题，等pngpaste的作者适配了就可以用了。

**Comment by xiebruce** [comment]
> [19:20:58.549] STDERR: PicUploaderHelper[Run Script] pngpaste: Could not write to file!

我又看了一下，这句报错貌似是没有权限，你看看你PicUploader是什么权限和组？如果是root，那肯定不行，你把它的所有者设置为你的用户名那个用户，比如我的用户名是bruce，我就设置为`chown -R bruce:staff ./PicUploader`这样，因为Alfred是系统用户的权限，它没有root权限去调用pngpaste。

**Comment by zzhi191** [comment]
PicUploader不是root权限,
就是当前登录用户的权限.
pngpaste: Could not write to file! 还存在,
我用python快捷键不影响使用😁

**Comment by xiebruce** [comment]
@zzhi191 好的，那应该是它没来得及更新适配新系统。

**Comment by zzhi191** [comment]
嗯嗯,好的,多谢!

**Comment by xiebruce** [comment]
@zzhi191 不客气，好用别忘了给个star呀！
