### ISSUE TITLE
设置图片水印卡在上传中无法成功上传

### ISSUE THREAD

**Issue by Eriky-git** [xiebruce/PicUploader#32]
当设置图片水印，会卡在上传中无法成功上传，文字水印没有问题，这是什么原因导致的呢？

**Comment by xiebruce** [comment]
你是用网页版还是右击上传？

**Comment by nanbabyer** [comment]
遇到了同样的问题，网页版

**Comment by xiebruce** [comment]
@nanbabyer 打开浏览器控制台，查看network里那个请求报什么错

**Comment by nanbabyer** [comment]
感谢博主回复


[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

以及


Unchecked runtime.lastError: The message port closed before a response was received.







------------------&nbsp;Original&nbsp;------------------

**Comment by xiebruce** [comment]
@nanbabyer 你再去看看PicUploader下的`logs`目录中的错误日志，最新一条错误是在最后的，你滚动到最后看看，贴上来

**Comment by nanbabyer** [comment]
感谢Thanks♪(･ω･)ﾉ


第一个问题回复：


看了一下log里面有11月和12月2个文件夹，每个里面有一个文档如下，
11月的：
2020-11-30 01:48:53(Gitee) =&gt; Client error: `POST https://gitee.com/api/v5/repos/insurewisely/Markdown/contents/images/4437756b4c4476494c955e7568c51e30.jpg` resulted in a `404 Not Found` response:
{"message":"Project"}




2020-11-30 11:58:27(Gitee) =&gt; Client error: `POST https://gitee.com/api/v5/repos/insurewisely/images/contents/images/c501df9e087378e6450f19a247c99b82.png` resulted in a `400 Bad Request` response:
{"messages":["message is empty"]}






12月的：
File uploaded to gitee at 2020-12-01 20:43:08 =&gt;&nbsp;
![image.jpg](https://gitee.com/insurewisely/images/raw/master/2020/12/01/fb34e0cc04ce1c3b2c43eedfc16eb0ae.jpg)





第二个问题，使用右键菜单的时候也报错。


我用过2种方法，第一个是替换水印，第二个是在后台配置。都不行。
复制完后也一直显示「上传中」


Notice: Undefined index: fontFile in /Users/nanbabyer/www/PicUploader/uploader/Common.php on line 129


Warning: getimagesize(/Users/nanbabyer/www/PicUploader/static/watermark//uploads/2020/11/30/e74b45b068df24129c106a35e97be7ab.png): failed to open stream: No such file or directory in /Users/nanbabyer/www/PicUploader/common/EasyImage.php on line 135


Notice: Trying to access array offset on value of type bool in /Users/nanbabyer/www/PicUploader/common/EasyImage.php on line 136


Fatal error: Uncaught Exception: Invalid image: /Users/nanbabyer/www/PicUploader/static/watermark//uploads/2020/11/30/e74b45b068df24129c106a35e97be7ab.png in /Users/nanbabyer/www/PicUploader/common/EasyImage.php:153
Stack trace:
#0 /Users/nanbabyer/www/PicUploader/common/EasyImage.php(106): common\EasyImage-&gt;load('/Users/nanbabye...')
#1 /Users/nanbabyer/www/PicUploader/common/EasyImage.php(741): common\EasyImage-&gt;__construct('/Users/nanbabye...')
#2 /Users/nanbabyer/www/PicUploader/uploader/Common.php(134): common\EasyImage-&gt;overlay('/Users/nanbabye...', 'center', '50', '-13', '-13')
#3 /Users/nanbabyer/www/PicUploader/uploader/Upload.php(142): uploader\Common-&gt;watermark('/Users/nanbabye...', '90')
#4 /Users/nanbabyer/www/PicUploader/index.php(166): uploader\Upload-&gt;getPublickLink(Array)
#5 {main}
&nbsp; thrown in /Users/nanbabyer/www/PicUploader/common/EasyImage.php on line 153




---







------------------&nbsp;Original&nbsp;------------------

**Comment by xiebruce** [comment]
你先试试关闭水印功能后，能不能上传

**Comment by nanbabyer** [comment]
可以用，文字水印都能用，只有图片水印用不了


------------------&nbsp;Original&nbsp;------------------

**Comment by xiebruce** [comment]
不好意思，是我没看清楚问题，我试了一下，这是个bug，因为我自己一直使用文字水印，所以没发现这个问题，现在已经修复，你更新一下就行。

**Comment by nanbabyer** [comment]
已更新，好用了！感谢！
还有个问题，我这里在图片上选择“右键菜单上传”还在报错。
过程如下：
1.点击图片，右键选择"使用picuploader上传"
2.上传时会在电脑屏幕右上角弹出“上传中”的提示如图：

3.图片消失，然后就没反应了。


4.我尝试直接粘贴，发现粘贴出来的是error信息，如下：


Warning: require_once(/Users/nanbabyer/www/PicUploader/GuzzleHttp/Client.php): failed to open stream: No such file or directory in /Users/nanbabyer/www/PicUploader/index.php on line 43


Fatal error: require_once(): Failed opening required '/Users/nanbabyer/www/PicUploader/GuzzleHttp/Client.php' (include_path='.:/usr/local/Cellar/php/7.4.12/share/php/pear') in /Users/nanbabyer/www/PicUploader/index.php on line 43





------------------&nbsp;Original&nbsp;------------------

**Comment by xiebruce** [comment]
1、给我看看你的”自动操作“里是怎么写的

2、你直接在终端执行命令看能不能上传，看看返回的报错是不是一样(其中`/path/to/test.jpg`换成你电脑里的一张图片的绝对路径)
```bash
php /Users/nanbabyer/www/PicUploader/index.php /path/to/test.jpg
```
3、你是上传到哪个云？
